using System.Collections.Generic;

public static class LibraryWords
{
    public static Localization language = new Localization("Русский", "English", "Français", "Italiano", "Deutsch", "Español", "中文", "Português", "한국어", "日本語", "Türk", "العربية", "हिन्दी", "Indonesian", "Polski", "Svensk");
    public static Localization music = new Localization("Музыка", "Music", "Musique", "Musica", "Musik", "Música", "音樂", "Música", "음악", "音楽", "Müzik", "موسيقى", "संगीत", "Musik", "Muzyka", "Muziki");
    public static Localization sounds = new Localization("Звуки", "Sounds", "Des sons", "Suoni", "Klingt", "sonidos", "聲音", "Sons", "소리", "音", "Sesler", "يبدو", "ध्वनि", "Kedengarannya", "Brzmi", "Sauti");
    public static Localization preciseControl = new Localization("Точное управление", "Precise Control", "Contrôle précis", "Controllo preciso", "Präzise Kontrolle", "Control preciso", "精確控制", "Controle Preciso", "정밀한 제어", "正確な制御", "Hassas Kontrol", "التحكم الدقيق", "सटीक नियंत्रण", "Kontrol yang Tepat", "Precyzyjna kontrola", "Udhibiti Sahihi");
    public static Localization flexibleManagement = new Localization("Гибкое управление", "Flexible control", "Contrôle flexible", "Controllo flessibile", "Flexible Steuerung", "control flexible", "控制靈活", "Controle flexível", "유연한 제어", "柔軟な制御", "Esnek kontrol", "تحكم مرن", "लचीला नियंत्रण", "Kontrol yang fleksibel", "Elastyczna kontrola", "Udhibiti rahisi");
    public static Localization startOver = new Localization("Начать заново", "Start again", "Recommencer", "Ricominciare", "Beginnen Sie erneut", "empezar de nuevo", "重新開始", "Começar de novo", "다시 시작", "もう一度始める", "Tekrar başla", "ابدأ مرة أخرى", "फिर से शुरू करें", "Mulai lagi", "Zacznij od nowa", "Anza tena");
    public static Localization reatings = new Localization("Рейтинги", "Ratings", "Notes", "Valutazioni", "Bewertungen", "Calificaciones", "評級", "Avaliações", "평가", "評価", "Derecelendirmeler", "التقييمات", "रेटिंग", "Peringkat", "Oceny", "Ukadiriaji");
    public static Localization shop = new Localization("Магазин", "Shop", "Boutique", "Negozio", "Geschäft", "Comercio", "店鋪", "Comprar", "가게", "店", "Mağaza", "محل", "दुकान", "Toko", "Sklep", "Duka");
    public static Localization level = new Localization("Уровень", "Level", "Niveau", "Livello", "Ebene", "Nivel", "等級", "Nível", "수준", "レベル", "Seviye", "مستوى", "स्तर", "Tingkat", "Poziom", "Kiwango");
    public static Localization dailyTasks = new Localization("Ежедневные Задания", "Daily Quests", "Quêtes quotidiennes", "Missioni giornaliere", "Tägliche Quests", "Misiones diarias", "每日任務", "Missões Diárias", "일일 퀘스트", "デイリークエスト", "Günlük Görevler", "المهام اليومية", "दैनिक प्रश्न", "Quest Harian", "Codzienne zadania", "Jumuia za Kila Siku");
    public static Localization dailyRewards = new Localization("Ежедневные Награды", "Daily Rewards", "Récompenses quotidiennes", "Premi giornalieri", "Tägliche Belohnungen", "Recompensas diarias", "每日獎勵", "Recompensas Diárias", "일일 보상", "毎日の報酬", "Günlük Ödüller", "المكافآت اليومية", "दैनिक पुरस्कार", "Hadiah Harian", "Codzienne nagrody", "Zawadi za Kila Siku");
    public static Localization wheelOfLuck = new Localization("Колесо Удачи", "Wheel of Fortune", "Roue de la Fortune", "Ruota della fortuna", "Glücksrad", "Rueda de la fortuna", "命運之輪", "Roda da fortuna", "행운의 수레바퀴", "運命の輪", "Çarkıfelek", "عجلة الحظ", "भाग्य का पहिया", "Roda peruntungan", "Koło fortuny", "Gurudumu la Bahati");
    public static Localization penguinTable = new Localization("Таблица Пингвинов", "Penguin Table", "Tableau Pingouin", "Tavolo Pinguino", "Pinguintisch", "Mesa Pingüino", "企鵝桌", "Mesa Pinguim", "펭귄 테이블", "ペンギンテーブル", "Penguen Masası", "جدول البطريق", "पेंगुइन टेबल", "Meja Pinguin", "Stół z pingwinami", "Jedwali la Penguin");
    public static Localization updatingVia = new Localization("Обновится через", "Will be updated in", "Sera mis à jour dans", "Verrà aggiornato in", "Wird aktualisiert in", "Se actualizará en", "將更新於", "Será atualizado em", "에 업데이트 예정", "に更新されます", "güncellenecektir", "سيتم التحديث في", "में अपडेट किया जाएगा", "Akan diperbarui di", "Zostanie zaktualizowany w", "Itasasishwa ndani");
    public static List<Localization> createPenguinTask = new List<Localization>()
    {
        new Localization("Создать пингвина первого уровня", "Create a level one penguin", "Créer un pingouin de niveau un", "Crea un pinguino di livello uno", "Erstelle einen Pinguin der Stufe 1", "Crea un pingüino de nivel uno.", "創建一級企鵝", "Crie um pinguim de nível um", "레벨 1 펭귄 만들기", "レベル 1 のペンギンを作成する", "Birinci seviye bir penguen yaratın", "إنشاء البطريق مستوى واحد", "एक लेवल वन पेंगुइन बनाएं", "Buat penguin tingkat satu", "Stwórz pingwina pierwszego poziomu", "Unda penguin ya kiwango cha kwanza"),
        new Localization("Создать пингвина второго уровня", "Create a level 2 penguin", "Créer un pingouin de niveau 2", "Crea un pinguino di livello 2", "Erstelle einen Pinguin der Stufe 2", "Crea un pingüino de nivel 2", "創建 2 級企鵝", "Crie um pinguim de nível 2", "레벨 2 펭귄 만들기", "レベル2のペンギンを作成する", "2. seviye penguen yaratın", "إنشاء البطريق المستوى 2", "लेवल 2 पेंगुइन बनाएं", "Buat penguin level 2", "Stwórz pingwina poziomu 2", "Unda penguin ya kiwango cha 2"),
        new Localization("Создать пингвина третьего уровня", "Create a level three penguin", "Créer un pingouin de niveau trois", "Crea un pinguino di livello tre", "Erstelle einen Pinguin der Stufe 3", "Crea un pingüino de nivel tres.", "創造三級企鵝", "Crie um pinguim de nível três", "레벨 3 펭귄 만들기", "レベル 3 のペンギンを作成する", "Üçüncü seviye bir penguen yaratın", "إنشاء البطريق المستوى الثالث", "लेवल तीन पेंगुइन बनाएं", "Buat penguin level tiga", "Stwórz pingwina trzeciego poziomu", "Unda penguin ya kiwango cha tatu"),
        new Localization("Создать пингвина четвёртого уровня", "Create a level four penguin", "Créer un pingouin de niveau quatre", "Crea un pinguino di livello quattro", "Erstelle einen Pinguin der Stufe 4", "Crea un pingüino de nivel cuatro.", "創造一隻四級企鵝", "Crie um pinguim de nível quatro", "레벨 4 펭귄 만들기", "レベル 4 のペンギンを作成する", "Dördüncü seviye bir penguen yaratın", "إنشاء البطريق المستوى الرابع", "लेवल चार का पेंगुइन बनाएं", "Buat penguin level empat", "Stwórz pingwina czwartego poziomu", "Unda penguin ya kiwango cha nne"),
        new Localization("Создать пингвина пятого уровня", "Create a level five penguin", "Créer un pingouin de niveau cinq", "Crea un pinguino di livello cinque", "Erstelle einen Pinguin der Stufe fünf", "Crea un pingüino de nivel cinco.", "創造五級企鵝", "Crie um pinguim de nível cinco", "레벨 5 펭귄 만들기", "レベル 5 のペンギンを作成する", "Beşinci seviye bir penguen yaratın", "إنشاء البطريق المستوى الخامس", "लेवल पांच का पेंगुइन बनाएं", "Buat penguin level lima", "Stwórz pingwina piątego poziomu", "Unda penguin ya kiwango cha tano"),
        new Localization("Создать пингвина шестого уровня", "Create a level six penguin", "Créer un pingouin de niveau six", "Crea un pinguino di livello sei", "Erstelle einen Pinguin der Stufe sechs", "Crea un pingüino de nivel seis.", "創造一隻六級企鵝", "Crie um pinguim de nível seis", "레벨 6 펭귄 만들기", "レベル6のペンギンを作成する", "Altıncı seviye bir penguen yaratın", "إنشاء البطريق المستوى السادس", "लेवल छह पेंगुइन बनाएं", "Buat penguin level enam", "Stwórz pingwina poziomu szóstego", "Unda penguin ya kiwango cha sita"),
        new Localization("Создать пингвина седьмого уровня", "Create a level seven penguin", "Créer un pingouin de niveau sept", "Crea un pinguino di livello sette", "Erstelle einen Pinguin der Stufe sieben", "Crea un pingüino de nivel siete.", "創造一隻七級企鵝", "Crie um pinguim de nível sete", "레벨 7 펭귄 만들기", "レベル7のペンギンを作成する", "Yedinci seviye bir penguen yaratın", "إنشاء البطريق المستوى السابع", "लेवल सात का पेंगुइन बनाएं", "Buat penguin level tujuh", "Stwórz pingwina siódmego poziomu", "Unda penguin ya kiwango cha saba"),
        new Localization("Создать пингвина восьмого уровня", "Create a level eight penguin", "Créer un pingouin de niveau huit", "Crea un pinguino di livello otto", "Erstelle einen Pinguin der Stufe acht", "Crea un pingüino de nivel ocho.", "創造一隻八級企鵝", "Crie um pinguim de nível oito", "레벨 8 펭귄 만들기", "レベル8のペンギンを作成する", "Sekizinci seviye bir penguen yaratın", "إنشاء البطريق المستوى الثامن", "लेवल आठ का पेंगुइन बनाएं", "Buat penguin level delapan", "Stwórz pingwina ósmego poziomu", "Unda penguin ya kiwango cha nane"),
        new Localization("Создать пингвина девятого уровня", "Create a level nine penguin", "Créer un pingouin de niveau neuf", "Crea un pinguino di livello nove", "Erstelle einen Pinguin der Stufe neun", "Crea un pingüino de nivel nueve.", "創建九級企鵝", "Crie um pinguim de nível nove", "레벨 9 펭귄 만들기", "レベル9のペンギンを作成する", "Dokuzuncu seviye bir penguen yaratın", "إنشاء البطريق المستوى التاسع", "लेवल नौ पेंगुइन बनाएं", "Buat penguin level sembilan", "Stwórz pingwina poziomu dziewiątego", "Unda penguin ya kiwango cha tisa"),
        new Localization("Создать пингвина десятого уровня", "Create a level ten penguin", "Créer un pingouin de niveau dix", "Crea un pinguino di livello dieci", "Erstelle einen Pinguin der Stufe zehn", "Crea un pingüino de nivel diez.", "創造一隻十級企鵝", "Crie um pinguim de nível dez", "레벨 10 펭귄 만들기", "レベル10のペンギンを作成する", "Onuncu seviye bir penguen yaratın", "إنشاء البطريق المستوى العاشر", "लेवल दस का पेंगुइन बनाएं", "Buat penguin level sepuluh", "Stwórz pingwina poziomu dziesiątego", "Unda penguin ya kiwango cha kumi"),
        new Localization("Создать пингвина одиннадцатого уровня", "Create a level eleven penguin", "Créer un pingouin de niveau onze", "Crea un pinguino di livello undici", "Erstelle einen Pinguin der Stufe 11", "Crea un pingüino de nivel once.", "創立十一級企鵝", "Crie um pinguim de nível onze", "레벨 11 펭귄 만들기", "レベル11のペンギンを作成する", "On birinci seviye bir penguen yaratın", "إنشاء البطريق المستوى الحادي عشر", "ग्यारहवें स्तर का पेंगुइन बनाएं", "Buat penguin level sebelas", "Stwórz pingwina jedenastego poziomu", "Unda penguin ya kiwango cha kumi na moja"),
        new Localization("Создать пингвина двенадцатого уровня", "Create a level twelve penguin", "Créer un pingouin de niveau douze", "Crea un pinguino di livello dodici", "Erstelle einen Pinguin der Stufe zwölf", "Crea un pingüino de nivel doce.", "創建十二級企鵝", "Crie um pinguim de nível doze", "레벨 12 펭귄 만들기", "レベル 12 のペンギンを作成する", "On iki seviyeli bir penguen yaratın", "إنشاء المستوى الثاني عشر البطريق", "लेवल बारह पेंगुइन बनाएं", "Buat penguin level dua belas", "Stwórz pingwina dwunastego poziomu", "Unda penguin ya kiwango cha kumi na mbili"),
        new Localization("Создать пингвина тринадцатого уровня", "Create a penguin of the thirteenth level", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня", "Создать пингвина тринадцатого уровня"),
        new Localization("Создать пингвина четырнадцатого уровня", "Create a level fourteen penguin", "Créer un pingouin de niveau quatorze", "Crea un pinguino di livello quattordici", "Erstelle einen Pinguin der Stufe 14", "Crea un pingüino de nivel catorce.", "創建十四級企鵝", "Crie um pinguim de nível quatorze", "레벨 14 펭귄 만들기", "レベル 14 のペンギンを作成する", "On dördüncü seviye bir penguen yaratın", "إنشاء المستوى الرابع عشر البطريق", "चौदह स्तर का पेंगुइन बनाएं", "Buat penguin level empat belas", "Stwórz pingwina na poziomie czternastym", "Unda penguin ya kiwango cha kumi na nne"),
        new Localization("Создать пингвина пятнадцатого уровня", "Create a level fifteen penguin", "Créer un pingouin de niveau quinze", "Crea un pinguino di livello quindici", "Erstelle einen Pinguin der Stufe 15", "Crea un pingüino de nivel quince.", "創造一隻十五級企鵝", "Crie um pinguim de nível quinze", "레벨 15 펭귄 만들기", "レベル15のペンギンを作成する", "Onbeşinci seviye bir penguen yaratın", "إنشاء المستوى الخامس عشر البطريق", "लेवल पंद्रह पेंगुइन बनाएं", "Buat penguin level lima belas", "Stwórz pingwina piętnastego poziomu", "Unda penguin ya kiwango cha kumi na tano"),
    };
    public static List<Localization> useBaffTask = new List<Localization>()
    {
            new Localization("Использовать усилитель \"мультимингвин\"", "Use the multiminguin booster", "Utilisez le booster multiminguin", "Usa il booster multiminguin", "Verwenden Sie den Multiminguin-Booster", "Usa el refuerzo multiminguin", "使用 multiminguin 助推器", "Use o reforço multiminguin", "멀티민구인 부스터를 사용해보세요", "マルチミンギンブースターを使用する", "Multiminguin güçlendiriciyi kullanın", "استخدم معززة multiminguin", "मल्टीमिंगुइन बूस्टर का प्रयोग करें", "Gunakan penguat multiminguin", "Użyj wzmacniacza multiminguin", "Tumia nyongeza ya multiminguin"),
            new Localization("Используйте усилитель «супер-пин»", "Use the \"super kick\" amplifier", "Utilisez l'amplificateur \"super kick\"", "Usa l'amplificatore \"super kick\".", "Verwenden Sie den „Super-Kick“-Verstärker", "Utilice el amplificador \"super kick\"", "使用“超級踢”放大器", "Use o amplificador \"super kick\"", "\"슈퍼킥\" 앰프를 사용하세요", "「スーパーキック」アンプを使用する", "\"Süper vuruş\" amplifikatörünü kullanın", "استخدم مضخم الصوت \"سوبر كيك\".", "\"सुपर किक\" एम्पलीफायर का उपयोग करें", "Gunakan penguat \"tendangan super\".", "Użyj wzmacniacza „super kick”.", "Tumia amplifier ya \"super kick\"."),
            new Localization("Используйте «бомбовый» усилитель", "Use the \"bomb\" amplifier", "Utilisez l'amplificateur \"bombe\"", "Usa l'amplificatore della \"bomba\".", "Verwenden Sie den „Bomben“-Verstärker", "Utilice el amplificador \"bomba\"", "使用“炸彈”放大器", "Use o amplificador \"bomba\"", "\"폭탄\" 증폭기를 사용하세요", "「爆弾」アンプを使用する", "\"Bomba\" amplifikatörünü kullanın", "استخدم مضخم الصوت \"القنبلة\".", "\"बम\" एम्पलीफायर का उपयोग करें", "Gunakan penguat \"bom\".", "Użyj wzmacniacza „bomby”.", "Tumia amplifier ya \"bomu\"."),
            new Localization("Используйте усилитель «ураган»", "Use the \"hurricane\" amplifier", "Utilisez l'amplificateur \"ouragan\"", "Usa l'amplificatore \"uragano\".", "Verwenden Sie den „Hurricane“-Verstärker", "Utilice el amplificador \"huracán\"", "使用“颶風”放大器", "Use o amplificador \"furacão\"", "\"허리케인\" 증폭기를 사용하세요", "「ハリケーン」アンプを使用する", "\"Kasırga\" amplifikatörünü kullanın", "استخدم مكبر الصوت \"الإعصار\".", "\"तूफान\" एम्पलीफायर का उपयोग करें", "Gunakan amplifier \"badai\".", "Użyj wzmacniacza „huraganowego”.", "Tumia kipaza sauti cha \"kimbunga\"."),
            new Localization("Используйте усилитель «Магнит»", "Use an amplifier \"magnet\"", "Utiliser un amplificateur « aimant »", "Utilizzare un \"magnete\" amplificatore", "Verwenden Sie einen Verstärker-„Magneten“.", "Utilice un amplificador \"imán\"", "使用擴大機“磁鐵”", "Use um amplificador \"ímã\"", "증폭기 \"자석\"을 사용하십시오.", "アンプ「マグネット」を使用する", "Bir amplifikatör \"mıknatıs\" kullanın", "استخدام مضخم الصوت \"المغناطيس\"", "एक एम्पलीफायर \"चुंबक\" का उपयोग करें", "Gunakan penguat \"magnet\"", "Użyj wzmacniacza „magnesu”", "Tumia amplifier \"sumaku\""),
    };
    public static Localization clickTask = new Localization("Кликнуть на экран, при создании пингвинов", "Click on the screen when creating penguins", "Cliquez sur l'écran lors de la création de pingouins", "Fai clic sullo schermo durante la creazione dei pinguini", "Klicken Sie beim Erstellen von Pinguinen auf den Bildschirm", "Haz clic en la pantalla al crear pingüinos.", "創建企鵝時點擊螢幕", "Clique na tela ao criar pinguins", "펭귄 생성시 화면을 클릭하세요", "ペンギン作成時に画面をクリック", "Penguenler oluştururken ekrana tıklayın", "انقر على الشاشة عند إنشاء طيور البطريق", "पेंगुइन बनाते समय स्क्रीन पर क्लिक करें", "Klik pada layar saat membuat penguin", "Kliknij ekran podczas tworzenia pingwinów", "Bofya kwenye skrini wakati wa kuunda penguins");
    public static Localization buy = new Localization("Купить", "Buy", "Acheter", "Acquistare", "Kaufen", "Comprar", "買", "Comprar", "구입하다", "買う", "Satın almak", "يشتري", "खरीदना", "Membeli", "Kupić", "Nunua");
    public static Localization spin = new Localization("Крутить", "Twist", "Torsion", "Intrecciare", "Twist", "Girar", "捻", "Torção", "트위스트", "ねじれ", "Büküm", "تطور", "मोड़", "Memutar", "Twist", "Twist");
    public static Localization get = new Localization("Получить", "Get", "Obtenir", "Ottenere", "Erhalten", "Conseguir", "得到", "Pegar", "얻다", "得る", "Elde etmek", "يحصل", "पाना", "Mendapatkan", "Dostawać", "Pata");
    public static Localization collect = new Localization("Собрать", "Collect", "Collecter", "Raccogliere", "Sammeln", "Recolectar", "收集", "Coletar", "모으다", "集める", "TOPLAMAK", "يجمع", "इकट्ठा करना", "Mengumpulkan", "Zbierać", "Kusanya");
    public static Localization collected = new Localization("Собрано", "Collected", "Collecté", "Raccolto", "Gesammelt", "Coleccionado", "集", "Coletado", "모은", "集めた", "Toplanan", "تم جمعها", "एकत्र किया हुआ", "Dikumpulkan", "Zebrane", "Imekusanywa");
    public static Localization you = new Localization("Вы", "You", "Toi", "Voi", "Du", "Tú", "你", "Você", "너", "あなた", "Sen", "أنت", "आप", "Anda", "Ty", "Wewe");
    public static Localization buyAttempt = new Localization("Купить попытку", "Buy a try", "Achetez un essai", "Acquista una prova", "Kaufen Sie einen Versuch", "Compra una prueba", "買來試試", "Compre uma tentativa", "한번 사용해 보세요", "試しに購入してみる", "Satın al, dene", "شراء محاولة", "एक कोशिश खरीदें", "Coba beli", "Kup próbę", "Nunua jaribu");
    public static Localization loginToGame = new Localization("Заходи в игру каждый день, чтобы получать награды!", "Log into the game every day to receive rewards!", "Connectez-vous au jeu tous les jours pour recevoir des récompenses !", "Accedi al gioco ogni giorno per ricevere premi!", "Melden Sie sich jeden Tag im Spiel an, um Belohnungen zu erhalten!", "¡Inicia sesión en el juego todos los días para recibir recompensas!", "每天登入遊戲即可領取獎勵！", "Entre no jogo todos os dias para receber recompensas!", "매일 게임에 로그인하여 보상을 받으세요!", "毎日ゲームにログインして報酬を受け取りましょう！", "Ödül almak için her gün oyuna giriş yapın!", "قم بتسجيل الدخول إلى اللعبة كل يوم لتحصل على المكافآت!", "पुरस्कार प्राप्त करने के लिए प्रतिदिन गेम में लॉग इन करें!", "Masuk ke dalam game setiap hari untuk menerima hadiah!", "Loguj się do gry codziennie, aby otrzymać nagrody!", "Ingia kwenye mchezo kila siku ili kupokea zawadi!");
    public static Localization received = new Localization("Получено", "Received", "Reçu", "Ricevuto", "Erhalten", "Recibió", "已收到", "Recebido", "받았다", "受け取った", "Kabul edilmiş", "تلقى", "प्राप्त", "Diterima", "Otrzymane", "Imepokelewa");
    public static Localization continueText = new Localization("Продолжить", "Continue", "Continuer", "Continuare", "Weitermachen", "Continuar", "繼續", "Continuar", "계속하다", "続く", "Devam etmek", "يكمل", "जारी रखना", "Melanjutkan", "Kontynuować", "Endelea");
    public static Localization doubleIt = new Localization("Удвоить", "Double", "Double", "Raddoppiare", "Doppelt", "Doble", "雙倍的", "Dobro", "더블", "ダブル", "Çift", "مزدوج", "दोहरा", "Dobel", "Podwójnie", "Mara mbili");
    public static Localization reward = new Localization("Премия", "Award", "Prix", "Premio", "Vergeben", "Otorgar", "獎", "Prêmio", "상", "賞", "Ödül", "جائزة", "पुरस्कार", "Menghadiahkan", "Nagroda", "Tuzo");
    public static Localization newLevel = new Localization("Новый уровень", "New level", "Nouveau niveau", "Nuovo livello", "Neues Level", "Nuevo nivel", "新水準", "Novo nível", "새로운 레벨", "新しいレベル", "Yeni seviye", "مستوى جديد", "नया स्तर", "tingkat baru", "Nowy poziom", "Kiwango kipya");

}